#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

# use snappyHexMesh to generate the mesh around the flat plate
(cd wingSnappy && ./Allclean)



# The background mesh
(cd backGroundAndWing  && ./Allclean)
